/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

/*

The data clearly shows the United States is our biggest market, with many more customers than any other country. 
Australia is the second most important market, while the UK, France, Germany, and Canada all have a similar, 
medium-sized customer base.

*/

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

/*
The customer base shows an extremely balanced distribution between male (9,341) and female (9,128) users, 
indicating equal general appeal of our product or service. 
*/

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

/*
The product assortment is heavily concentrated in the Components (127) and Bikes (97) categories, 
establishing the business as a primary retailer of core cycling equipment. Clothing (35) and Accessories (29) 
represent smaller, secondary categories that should be further analyzed for potential inventory expansion.
*/

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

/*
The data confirms that Bikes have a significantly dominant average cost of $949, making efficient inventory and 
sales management for this category critical for financial success. Components ($264) represent a moderate-cost inventory,
while Clothing ($24) and Accessories ($13) act as low-cost, high-volume segments ideal for cross-selling strategies. 
Finally, the NULL category with a cost of $28 demands immediate data cleanup to ensure all product costs are accurately 
assigned for proper financial reporting.

*/

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
